server:
  port: 8080
  error:
    include_message: always
    include-binding-errors: always
                                          # Remember to change your database to fit with it
spring:                                   #      ||
  datasource:                            #       V
    url: jdbc:mysql://localhost:3306/online_exam_db
    username: #INSERT YOUR USERNAME
    password: #INSERT YOUR PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #IMPROVE THE READABLE FOR CODE
      ddl-auto:
    show-sql: true